### ISSUE TITLE
0 is returned by many values and breaks some customizers

### ISSUE THREAD

**Issue by AnimbusDev** [afollestad/app-theme-engine#60] opened 2016-01-11 04:14 UTC
So with the new returning 0 to disable a customiser, I realised Color.BLACK always returns 0, disabling the customiser. So this value (the one that disables the customiser) needs to be changed to -1. Also, things like status bar customiser glitches, because 0 is auto, and 0 disables.

**Comment by afollestad** [comment] 2016-01-11 04:15
If I remember correctly, there are some colors representations in Java that are less than 0. So I don't think using -1 is safe for that.

**Comment by AnimbusDev** [comment] 2016-01-11 04:19
@afollestad You can define a variable in ATE.javajava to be used and have it be some crazy random negative number. If any issues come up, you can just change it.

**Comment by afollestad** [comment] 2016-01-11 18:55
@AnimbusDev it actually looks like almost *all* colors are negative in Java: http://developer.android.com/reference/android/graphics/Color.html

So we might actually need to use the max positive value of an Integer.

**Comment by afollestad** [comment] 2016-01-11 19:00
But I'm not 100% sure about that.

**Comment by afollestad** [comment] 2016-01-11 19:05
Also, you should return the `Config` constants for the light mode methods. Not doing so should give you a warning anyways, since they are IntDefs.

**Comment by AnimbusDev** [comment] 2016-01-11 20:09
@afollestad I do return the config constants. The issue is one of the constants _is_ 0...

**Comment by afollestad** [comment] 2016-01-11 20:10
@AnimbusDev I'd change it, but it'd break apps that already have that configuration value set (since they're stored in shared preferences). It shouldn't be that much of an issue though.

**Comment by AnimbusDev** [comment] 2016-01-11 20:11
@afollestad changing 0 to the Max int would fix that anyways...

**Comment by afollestad** [comment] 2016-01-11 23:20
Removed use of 0 for the light mode constants in the last commit (referencing this issue).

---

I've confirmed that Android colors are negative, I'm not sure if any are positive at all:

<img width="624" alt="screen shot 2016-01-11 at 5 18 22 pm" src="https://cloud.githubusercontent.com/assets/1820165/12249781/908b9a04-b887-11e5-83a8-bf8f5879ae08.png">

**Comment by afollestad** [comment] 2016-01-17 21:28
Closing this since there's not really good solution for this. You should just avoid returning 0 and use the `Config` static methods where you want defaults to be used.

**Closed by afollestad** 2016-01-17 21:28 UTC
Labels: tweak

**Comment by AnimbusDev** [comment] 2016-01-17 21:30
@afollestad There was a valid solution to this already...

Just have a stitic int (ATE.IGNORE_CUSTOMIZER) be the Max int value. Then just have it check for that instead of 0. Problem solved

**Comment by afollestad** [comment] 2016-01-17 21:31
That's not necessarily a safe solution, and that's really not that much more work than returning a Config method value.

**Comment by AnimbusDev** [comment] 2016-01-17 21:33
What? No but black is 0, and black is used a ton more then you expect. Really, this causes a lot of issues in my app, and I really doubt that there is a color that is the Max int (most are negative)

**Comment by afollestad** [comment] 2016-01-17 21:39
https://github.com/afollestad/app-theme-engine/commit/02694a17ec6acebbd25aa6806d997de4b586e3e0

**Comment by kabouzeid** [comment] 2016-01-17 23:20
@afollestad all integers represent a color. 32 bit in hexadezimal 0x00000000 - 0xFFFFFFFF
(AA RR GG BB). Because you've only tried opaque colors the very left bit (which is used for the sign when interpreting the bits as a number) is set to 1 which means minus. Actually 0 isn't black but transparent. Black would be FF000000 -> some negative number as well. Everything with alpha > 7F (127) will be negative.

**Comment by afollestad** [comment] 2016-01-17 23:23
@kabouzeid thanks for the info! I had forgotten most of what I had memorized about hexadecimals 😁
