### ISSUE TITLE
Search view theming broken when immediately expanded

### ISSUE THREAD

**Issue by AnimbusDev** [afollestad/app-theme-engine#50] opened 2016-01-06 22:39 UTC
![screenshot_20160106-173719](https://cloud.githubusercontent.com/assets/11251606/12156979/42a3bffe-b49c-11e5-8b0d-1b39cd8ac528.png)
Here is the issue. It fixes if I exit the activity and return.(press home or multitasking and come back for example).

**Comment by afollestad** [comment] 2016-01-06 22:40
I've had no issues with this.

**Comment by AnimbusDev** [comment] 2016-01-06 22:44
@afollestad I think it's because I expand it instantly in on create. Her is my code: https://github.com/Substance-Project/GEM/blob/indev/mobile/src/main/java/com/animbus/music/ui/activity/search/SearchActivity.java

**Comment by afollestad** [comment] 2016-01-06 23:35
Even when expand the SearchView from `onCreateOptionsMenu` immediately, the text is fine. I only have an issue with the search icon (while expanded) in the light theme, so something obviously has to be fixed somewhere.

![affix_20160106_173417](https://cloud.githubusercontent.com/assets/1820165/12158007/cb69df5e-b49b-11e5-8083-629c471337b3.png)

**Comment by AnimbusDev** [comment] 2016-01-06 23:39
The issue only happens on a light theme dark primary configuration (just messed around)

If that doesnt work, try getting rid of anything else from the menu for 
the time being. Just the search.

**Comment by afollestad** [comment] 2016-01-10 04:07
@AnimbusDev not able to reproduce it with a dark primary color with the light theme either:

<img width="497" alt="screen shot 2016-01-09 at 10 07 12 pm" src="https://cloud.githubusercontent.com/assets/1820165/12219912/69a265a0-b71d-11e5-9f80-e0d3b545722a.png">

**Comment by afollestad** [comment] 2016-01-10 04:14
You may wanna try the latest code to see if it's been fixed somehow.

**Comment by AnimbusDev** [comment] 2016-01-10 05:12
@afollestad And I cannot reproduce that search icon... Are you expanding it the same way I am in my code? Also, I will try the new update when I have a chance (tomorrow probably)

**Comment by AnimbusDev** [comment] 2016-01-10 05:20
@afollestad I just went through to the android:theme and set it to what you have in the sample.

Now it happenes whenever the primary is light with any base

**Comment by afollestad** [comment] 2016-01-10 06:43
The only cause I can think of is if you were using the stock `SearchView` (`android.widget.SearchView`) rather than the support SearchView included with AppCompat.

**Comment by afollestad** [comment] 2016-01-10 19:51
Nevermind, even with `android.widget.SearchView`, it works fine for me.

**Comment by afollestad** [comment] 2016-01-12 02:35
I'll be closing this tomorrow if no further problems are reported

**Comment by AnimbusDev** [comment] 2016-01-12 02:39
@afollestad I have no idea why it is like this. It just is, when I resume the activity it themes properly

**Comment by afollestad** [comment] 2016-01-28 03:22
This is probably fixed in the newer code since inflater factories are used instead of looping over already inflated views.

**Closed by afollestad** 2016-01-28 03:22 UTC
Labels: possible bug, unable to reproduce
