### ISSUE TITLE
0.7.5 release crash issue

### ISSUE THREAD

**Issue by PDDStudio** [afollestad/app-theme-engine#56] opened 2016-01-10 13:29 UTC
Upgrading from v 0.7.0 to 0.7.5 - nothing else has changed (only the library version in the gradle file)

When assembling and running the debug app it crashes on the MainActivity's onCreate().

**Exception:**
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.pddstudio.pur/com.pddstudio.pur.MainActivity}: android.view.InflateException: Binary XML file line #52: Binary XML file line #52: Error inflating class TextView
```

Downgrading to 0.7.0 works again without any problems. Tested it with normal TextView and ATE's PrimaryTextView, both are throwing the same exception.

[Paste of the complete error](http://pastebin.com/8YVM3CX6)

The TextView which throws this exception is wrapped with an ImageView into an CollapsingToolbarLayout.

Please let me know if you need further information.

**Comment by afollestad** [comment] 2016-01-10 17:37
There must be an attribute or attribute value being used in your app/XML
that causes the error

On Sun, Jan 10, 2016, 7:29 AM Patrick J <notifications@github.com> wrote:

> Upgrading from v 0.7.0 to 0.7.5 - nothing else has changed (only the
> library version in the gradle file)
>
> When assembling and running the debug app it crashes on the MainActivity's
> onCreate().
>
> *Exception:*
>
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.pddstudio.pur/com.pddstudio.pur.MainActivity}: android.view.InflateException: Binary XML file line #52: Binary XML file line #52: Error inflating class TextView
>
> Downgrading to 0.7.0 works again without any problems. Tested it with
> normal TextView and ATE's PrimaryTextView, both are throwing the same
> exception.
>
> Paste of the complete error <http://pastebin.com/8YVM3CX6>
>
> The TextView which throws this exception is wrapped with an ImageView into
> an CollapsingToolbarLayout.
>
> Please let me know if you need further information.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afollestad/app-theme-engine/issues/56>.
>
-- 

Regards,

Aidan Follestad
http://aidanfollestad.com
651-528-1662

**Comment by afollestad** [comment] 2016-01-10 18:48
It looks like the important part of that log is:

```Gradle
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x2/d=0x101009b a=1}
        at android.content.res.TypedArray.getColorStateList(TypedArray.java:482)
        at android.widget.TextView.<init>(TextView.java:750)
```

So there must be an attribute you change in your app which for whatever reason is not compatible.

**Comment by afollestad** [comment] 2016-01-10 19:46
Since this log doesn't take place inside of this library and I can't reproduce it, I'm closing the issue

**Comment by PDDStudio** [comment] 2016-01-10 21:21
The question is what exactly is causing this bug? 0.7.0 is working fine, when updating to 0.7.5 it's crashing, so I has to be bug in the library

**Comment by julian200601** [comment] 2016-01-10 21:25
@PDDStudio post the xml

**Comment by PDDStudio** [comment] 2016-01-11 06:01
@julian200601 I'll attach the xml as soon as I'm on my pc. Even tho this shouldn't be the problem, all I'm using are default Android kv attributes

**Comment by PDDStudio** [comment] 2016-01-13 19:16
Seems like 0.7.6 fixed it, it's working fine now

**Comment by afollestad** [comment] 2016-01-13 19:17
0.7.7 is the latest 😉but great!

**Closed by afollestad** 2016-01-13 19:17 UTC
Labels: high priority, possible bug, unable to reproduce

**Comment by PDDStudio** [comment] 2016-01-14 11:56
@afollestad yeah I know, i mean it's working again since +0.7.6 😀
